//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionPoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.service1 = new HashSet<service1>();
        }
    
        public int employee_id { get; set; }
        public string e_name { get; set; }
        public System.DateTime e_admission_date { get; set; }
        public string e_active { get; set; }
        public int e_supervisor { get; set; }
        public string e_observation { get; set; }
        public string e_certificate { get; set; }
        public byte[] e_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service1> service1 { get; set; }
    }
}
