//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionPoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service1
    {
        public int service_id { get; set; }
        public Nullable<System.DateTime> service_date { get; set; }
        public Nullable<int> employee_attend { get; set; }
        public Nullable<int> client_attended { get; set; }
        public string activity { get; set; }
    
        public virtual client client { get; set; }
        public virtual employee employee { get; set; }
    }
}
