//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionPoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supervisor
    {
        public int supervisor_id { get; set; }
        public string s_name { get; set; }
        public string s_area { get; set; }
        public string s_active { get; set; }
    }
}
